#!/bin/bash
name=$(jq -r '.name' pokemon.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' pokemon.json | sed 's/.*/\u&/')
formatted_weight=$(jq -r '.weight' pokemon.json | awk '{printf "%.0f", $1/10}')
formatted_height=$(jq -r '.height' pokemon.json | awk '{printf "%.1f", $1/10}')
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
